FROM nginx:1.21.6-alpine

COPY . /usr/share/nginx/html/
COPY ./docker.conf/default.dev.conf /etc/nginx/conf.d/default.conf

ENV HTML_ENV development

RUN chmod +x /usr/share/nginx/html/env.sh
RUN /usr/share/nginx/html/env.sh

